inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - "config/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "Gemfile"
    - "Gemfile.lock"
    - "test/**/*"
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 198

Style/Documentation:
  Enabled: false